---
singletons:
- javax.sql.DataSource:
  - com.zaxxer.hikari.HikariDataSource:
      DriverClassName: org.h2.jdbcx.JdbcDataSource
      jdbcUrl: jdbc:h2:~/test
      username: sa
      password: sa
- com.networknt.saga.core.message.producer.MessageProducer:
  - com.networknt.saga.repository.MessageProducerJdbcImpl
