---
singletons:
- com.networknt.tram.message.consumer.MessageConsumer:
  - com.networknt.tram.consumer.kafka.MessageConsumerKafkaImpl
- com.networknt.saga.orchestration.SagaInstanceRepository:
  - com.networknt.saga.orchestration.SagaInstanceRepositoryJdbc
- com.networknt.saga.participant.SagaLockManager:
  - com.networknt.saga.participant.SagaLockManagerImpl
- com.networknt.saga.orderservice.customer.domain.CustomerRepository:
  - com.networknt.saga.orderservice.customer.domain.MapCustomerRepository
- com.networknt.saga.orderservice.order.domain.OrderRepository:
  - com.networknt.saga.orderservice.order.domain.MapOrderRepository
- com.networknt.saga.orderservice.order.saga.createorder.CreateOrderSagaData:
  - com.networknt.saga.orderservice.order.saga.createorder.CreateOrderSagaData
- com.networknt.saga.orderservice.customer.service.CustomerService:
  - com.networknt.saga.orderservice.customer.service.CustomerService
- com.networknt.saga.orderservice.customer.service.CustomerCommandHandler:
  - com.networknt.saga.orderservice.customer.service.CustomerCommandHandler
- com.networknt.saga.orderservice.order.service.OrderCommandHandler:
  - com.networknt.saga.orderservice.order.service.OrderCommandHandler
- com.networknt.saga.orderservice.order.saga.createorder.CreateOrderSaga:
  - com.networknt.saga.orderservice.order.saga.createorder.CreateOrderSaga